/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MyQuotesRouteImport } from './routes/my-quotes'
import { Route as MyPaymentsRouteImport } from './routes/my-payments'
import { Route as MyDocumentsRouteImport } from './routes/my-documents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuotesNewRouteImport } from './routes/quotes/new'
import { Route as QuotesQuoteIdRouteImport } from './routes/quotes/$quoteId'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQuotesRoute = MyQuotesRouteImport.update({
  id: '/my-quotes',
  path: '/my-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPaymentsRoute = MyPaymentsRouteImport.update({
  id: '/my-payments',
  path: '/my-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDocumentsRoute = MyDocumentsRouteImport.update({
  id: '/my-documents',
  path: '/my-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesNewRoute = QuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuotesRoute,
} as any)
const QuotesQuoteIdRoute = QuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => QuotesRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/fiscal': typeof FiscalRoute
  '/login': typeof LoginRoute
  '/my-documents': typeof MyDocumentsRoute
  '/my-payments': typeof MyPaymentsRoute
  '/my-quotes': typeof MyQuotesRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/quotes/new': typeof QuotesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/fiscal': typeof FiscalRoute
  '/login': typeof LoginRoute
  '/my-documents': typeof MyDocumentsRoute
  '/my-payments': typeof MyPaymentsRoute
  '/my-quotes': typeof MyQuotesRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/quotes/new': typeof QuotesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/fiscal': typeof FiscalRoute
  '/login': typeof LoginRoute
  '/my-documents': typeof MyDocumentsRoute
  '/my-payments': typeof MyPaymentsRoute
  '/my-quotes': typeof MyQuotesRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/quotes/new': typeof QuotesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/fiscal'
    | '/login'
    | '/my-documents'
    | '/my-payments'
    | '/my-quotes'
    | '/payments'
    | '/profile'
    | '/quotes'
    | '/register'
    | '/reports'
    | '/settings'
    | '/admin/dashboard'
    | '/quotes/$quoteId'
    | '/quotes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/fiscal'
    | '/login'
    | '/my-documents'
    | '/my-payments'
    | '/my-quotes'
    | '/payments'
    | '/profile'
    | '/quotes'
    | '/register'
    | '/reports'
    | '/settings'
    | '/admin/dashboard'
    | '/quotes/$quoteId'
    | '/quotes/new'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/dashboard'
    | '/fiscal'
    | '/login'
    | '/my-documents'
    | '/my-payments'
    | '/my-quotes'
    | '/payments'
    | '/profile'
    | '/quotes'
    | '/register'
    | '/reports'
    | '/settings'
    | '/admin/dashboard'
    | '/quotes/$quoteId'
    | '/quotes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  DashboardRoute: typeof DashboardRoute
  FiscalRoute: typeof FiscalRoute
  LoginRoute: typeof LoginRoute
  MyDocumentsRoute: typeof MyDocumentsRoute
  MyPaymentsRoute: typeof MyPaymentsRoute
  MyQuotesRoute: typeof MyQuotesRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  QuotesRoute: typeof QuotesRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-quotes': {
      id: '/my-quotes'
      path: '/my-quotes'
      fullPath: '/my-quotes'
      preLoaderRoute: typeof MyQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-payments': {
      id: '/my-payments'
      path: '/my-payments'
      fullPath: '/my-payments'
      preLoaderRoute: typeof MyPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-documents': {
      id: '/my-documents'
      path: '/my-documents'
      fullPath: '/my-documents'
      preLoaderRoute: typeof MyDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/new': {
      id: '/quotes/new'
      path: '/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof QuotesNewRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/quotes/$quoteId': {
      id: '/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof QuotesQuoteIdRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QuotesRouteChildren {
  QuotesQuoteIdRoute: typeof QuotesQuoteIdRoute
  QuotesNewRoute: typeof QuotesNewRoute
}

const QuotesRouteChildren: QuotesRouteChildren = {
  QuotesQuoteIdRoute: QuotesQuoteIdRoute,
  QuotesNewRoute: QuotesNewRoute,
}

const QuotesRouteWithChildren =
  QuotesRoute._addFileChildren(QuotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  DashboardRoute: DashboardRoute,
  FiscalRoute: FiscalRoute,
  LoginRoute: LoginRoute,
  MyDocumentsRoute: MyDocumentsRoute,
  MyPaymentsRoute: MyPaymentsRoute,
  MyQuotesRoute: MyQuotesRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  QuotesRoute: QuotesRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
